# Generated by Django 5.2.6 on 2025-10-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_usuario', to='abm.userprofile'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia_cliente', to='abm.cliente'),
        ),
    ]
