# Generated by Django 5.2.6 on 2025-10-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0002_alter_cliente_usuario_id_alter_membresia_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
