# Generated by Django 5.2.6 on 2025-10-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0003_cliente_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='importe',
        ),
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('importe', models.FloatField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=30)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to='abm.membresia')),
            ],
        ),
    ]
