# Generated by Django 5.2.6 on 2025-10-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0004_remove_membresia_importe_cobranza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
