# Generated by Django 5.2.6 on 2025-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm', '0005_rename_cliente_id_asistencia_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='asistencia',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_clase',
            field=models.DateField(auto_now_add=True),
        ),
    ]
