# Generated by Django 5.2.6 on 2025-10-02 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.IntegerField()),
                ('peso', models.FloatField()),
                ('objetivo', models.CharField(blank=True, default='', max_length=300)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=80)),
                ('dni', models.IntegerField(unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='domicilio',
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='provincia',
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.IntegerField(default=0)),
                ('horaInicio', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('capacidad', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('antiguedad', models.SmallIntegerField(default=0)),
                ('especialidad', models.TextField(blank=True, default='')),
                ('turno', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('monto', models.FloatField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
