# Generated by Django 5.2.6 on 2025-10-06 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_usuario_remove_persona_domicilio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='membresia',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='membresia',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='membresia',
            old_name='monto',
            new_name='importe',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
        migrations.AddField(
            model_name='membresia',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('adeuda', 'Adeuda'), ('baja', 'Baja')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.IntegerField(default=0)),
                ('fecha_clase', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('capacidad', models.IntegerField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=150)),
                ('fecha_nac', models.DateField()),
                ('firstLogin', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
