# Generated by Django 5.2.6 on 2025-10-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_empleado_usuario_remove_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstLogin',
            new_name='first_login',
        ),
    ]
