# Generated by Django 5.2.6 on 2025-10-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_firstlogin_userprofile_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Adeuda', 'Adeuda'), ('Baja', 'Baja')], max_length=50),
        ),
    ]
