# Generated by Django 5.2.6 on 2025-10-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_membresia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Membresia',
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
